version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8@sha256:fbb00f61f4c5b0d4406e327741b1cacd3409eba7497a964b159828ff8690bc30

jobs:
  clone:
    <<: *defaults
    docker:
      - image: circleci/node:8@sha256:fbb00f61f4c5b0d4406e327741b1cacd3409eba7497a964b159828ff8690bc30
    steps:
      - checkout
  testing:
    docker:
      - image: circleci/node:8@sha256:fbb00f61f4c5b0d4406e327741b1cacd3409eba7497a964b159828ff8690bc30
    steps:
      - checkout
      - restore_cache:
          name : Restore node modules Cache
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: yarn
      - save_cache:
          name: Save node modules cache
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Tests
      - run:
          name: Check for Linting Errors
          command: yarn lint
      - run:
          name: Run Unit Tests
          command: |
            ./cc-test-reporter before-build
            yarn coverage
            ./cc-test-reporter after-build --coverage-input-type lcov -r ${CODECLIMATE_TEST_REPORTER_ID}

workflows:
  version: 2

  clone-and-test:
    jobs:
      - clone
      - testing:
          requires:
            - clone