# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BetterApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BetterApp
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.5'
  pod 'Crashlytics', '~> 3.10.1'

  target 'BetterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
